export const dataOfCurr = [
  {name:'USD',"symbol": "$"},
  {name:'AUD',"symbol": "$"},
  {name:'BRL',"symbol": "R$"},
  {name:'CAD',"symbol": "CHF"},
  {name:'CHF',"symbol": "$"},
  {name:'CLP',"symbol": "$"},
  {name:'CNY',"symbol": "¥"},
  {name:'DKK',"symbol": "kr"},
  {name:'EUR',"symbol": "€"},
  {name:'GBP',"symbol": "£"},
  {name:'HKD',"symbol": "$"},
  {name:'INR',"symbol": "₹"},
  {name:'ISK',"symbol": "kr"},
  {name:'JPY',"symbol": "¥"},
  {name:'KRW',"symbol": "₩"},
  {name:'NZD',"symbol": "$"},
  {name:'PLN',"symbol": "zł"},
  {name:'RUB',"symbol": "RUB"},
  {name:'SEK',"symbol": "kr"},
  {name:'SGD',"symbol": "$"},
  {name:'THB',"symbol": "฿"},
  {name:'TRY',"symbol": "₺"},
  {name:'TWD',"symbol": "NT$"},
]